### ISSUE TITLE
Symmetrizing weights/mask

### ISSUE THREAD

**Issue by DhayaaAnbajagane** [seccolf/measure_shear#4]
Currently, we symmetrize the mask in the preprocessing meds stage of metacal, and then we interpolate across the good pixels to fill bad pixels. The ordering of this needs to be checked, do we:

1. Symmetrize mask first + then interpolate (this is what we do now, with function calls found [here](https://github.com/seccolf/measure_shear/blob/4b4cbb2b8b029ea1c9992205e8eaa350aee71b48/run_utils.py#L80) and [here](https://github.com/seccolf/measure_shear/blob/4b4cbb2b8b029ea1c9992205e8eaa350aee71b48/run_utils.py#L84) and functions themselves in [here](https://github.com/seccolf/measure_shear/blob/main/meds_preprocess/preprocess.py))
2. Or interpolate and then symmetrize mask (i.e. we only interpolate over bad pix with good pix defined using the true mask, and then symmetrized mask to pass into mcal. Maybe inconsistent to do this?)

I can definitely just do each version and check difference.

--------------------

Do we need to also do weights=0 to reflect the masking or is that taken care of internally in metacal? (for example does metacal never use any pixel that has bmask!=0) ?

--------------------

Do we need to do anything special for 2**30 edge masks when we symmetrize? The current symmetrization leaves is just binary True/False rather than a bit mask (due to a astype(bool) done [here](https://github.com/seccolf/measure_shear/blob/4b4cbb2b8b029ea1c9992205e8eaa350aee71b48/meds_preprocess/preprocess.py#L147)). Do we need to do a bitwise_or to merge true bmask and rotated bmask?

**Comment by beckermr** [comment]
We symmetrize before interpolation. 

Def check weights == 0 to. I thought we were.

Always "or" bit masks.

**Comment by DhayaaAnbajagane** [comment]
Thanks, that helps! Interpolation part can stay as is then, and I will implement the bitwise_or operators instead of the boolean ones.

For 2, is the suggestion to use weights==0 as an additional mask, so something like `Mask = (weights == 0) | (bmask != 0)`? Or is the suggestion that I should explicity set weights=0 wherever bmask != 0, i.e. `weights[bmask != 0] = 0`? I'd been thinking about latter in my question but wasn't sure which one you were suggesting above.

**Comment by beckermr** [comment]
Yes using weights == 0 as an additional mask is fine.

**Comment by DhayaaAnbajagane** [comment]
Implemented in commit 351986859c886eceba353074dde3e12b2d762a1d. `Weights == 0` is now included as additional mask plane. At the end of all the pre-processing steps, all masked pixels have weights set as `weights=0`. Probably okay to set this for just a subset of the bitmask, but doing it for all for the moment. Image sims did not show any bias from doing this choice.
